# Generated by Django 5.2.1 on 2025-05-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('discapacitado', 'Discapacitado')], max_length=20)),
                ('valor_por_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_por_dia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_dia_festivo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('discapacitado', 'Discapacitado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('zona_carros', 'Zona Carros'), ('zona_motos', 'Zona Motos'), ('zona_discapacitados', 'Zona Discapacitados')], max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('ocupados', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('cobro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='zona_asignada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueadero.zona'),
        ),
    ]
