# Generated by Django 5.2.1 on 2025-06-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_configuracionsistema_promocion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Comprobante'),
        ),
        migrations.AddField(
            model_name='pago',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueadero.empleado', verbose_name='Empleado que registró'),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago'),
        ),
        migrations.AddField(
            model_name='registroparqueo',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registroparqueo',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parqueadero.zona'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('app', 'Aplicación Móvil')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='registro_parqueo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='parqueadero.registroparqueo', verbose_name='Registro de Parqueo'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='parqueadero_fecha_p_f01aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='parqueadero_estado_947667_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='parqueadero_metodo__b562bb_idx'),
        ),
    ]
