# Generated by Django 5.2.1 on 2025-06-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0003_espacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueadero.espacio'),
        ),
    ]
