# Generated by Django 5.2.1 on 2025-06-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0005_propietario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
